### ISSUE TITLE
Accessing tenant tables data dynamically according to tenant which is requested at browser url

### ISSUE THREAD

**Issue by ramukodandapuram** [bertini36/multitenancy#1]
Hi @bertini36  
                   I have two tenant schemas called tenant1, tenant2  each having table called contact again it contains some rows of data. now I wanted to access contact table data for particular tenant schema which is requested at browser url. for suppose  **http://tenant2.trendy-sass.com:8000/contacts/**
I followed your repo on github  and understood somehow ,as a newbie struggling little bit please help me out of this.
thanks in advance.

**Comment by bertini36** [comment]
Hi @ramukodandapuram 

If all is ok you would have a client table in public schema. Then if you want to connect with a particular tenant you have to query this table:

```
from django.db import connection
from customers.models import Client

tenant = Client.objects.get(name='Tenant 1')
connection.set_tenant(tenant)
```

I don't remember exactly but I think that if you have configured settings right you have added the Django tenant middleware then, in a concrete view, if you import a concrete model a query will be applied to the requested schema. 

```
MIDDLEWARE_CLASSES = (
    'tenant_schemas.middleware.TenantMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
   ...
)
```
